apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: ntlg-k8s-mon
spec:
  environments:
    prod:
      defaultNamespace: monitoring
      server: https://10.0.2.15:16443
  vars:
    computed:
      - name: helmValues
        code: |
          local p = import './params.libsonnet';
          local params = p.components.monitoring;
          local ns = std.extVar('qbec.io/defaultNs');
          local env = std.extVar('qbec.io/env');
          {
            command: "helm",
            args: [ "install", "--repo", params.repo, env, params.chart_name, "--namespace", ns, "--debug" ],
            env: {
              KUBECONFIG: params.kube_config
            },
            timeout: "300s"
          }
  dataSources:
    - exec://helmInstall?configVar=helmValues
